kramdown:
   input: GFM
   hard_wrap: false
gems:
   - jekyll-assets
   - jekyll-feed

exclude: [LICENSE.md, config.ru, Gemfile, Gemfile.lock, Procfile, rakefile.rb, README.md, vendor, _drafts]

owner-name: brendan forster
owner-page: http://brendanforster.com
owner-email: me@brendanforster.com

license: bsd

# feed options
feed:
  path: atom.xml

name: brendan forster
url: http://brendanforster.com
author:
  name: Brendan Forster
  email: me@brendanforster.com
