auto: false
pygments: true

markdown: rdiscount

exclude: [LICENSE.md, config.ru, Gemfile, Gemfile.lock, Procfile, rakefile.rb, README.md, vendor]

owner-name: brendan forster
owner-page: http://brendanforster.com
owner-email: me@brendanforster.com

license: bsd