auto: true

markdown: rdiscount

exclude: ["README.md", "LICENSE.md", "TODO.md", "test"]

owner-name: brendan forster
owner-page: http://brendanforster.com
owner-email: me@brendanforster.com

license: bsd